---
title: Mấy bài nhạc cũ mèm
tags:
  - music
date: 2023-12-18
description: gu âm nhạc của tôi khi nói về thế hệ trước
slug: may-bai-nhac-cu-mem
---

== The Great Pretender (1955) -The Platters

image::1.avif[The Platters,height=300,align=center]

[.text-center]
====
____
_Đúng vậy... anh là kẻ giỏi giả vờ, giả vờ là anh vẫn ổn_

_Anh đội trái tim mình như vương miện, giả vờ như em vẫn còn ở bên._
____
====

Bài hát được viết trong 20 phút trong phòng giặt đồ bởi trưởng nhóm The Platters. Nói đến những bài có độ cũ thế này, tôi thích luyện tai mình bằng cách nghe ra tất cả giọng bè và cách chuyển tiết tấu, hòa âm của mấy nhạc cụ được dùng trong bài... sở thích lạ đời của một thằng sinh viên thanh nhạc...

Nghe thử tại https://www.youtube.com/watch?v=IEzfhclKO8Q[YouTube].

== The End Of The World (1962) - Skeeter Davis

image::2.avif[Skeeter Davis,width=300,align=center]

[.text-center]
====
____
_Ngày anh nói tạm biệt cũng là lúc thế giới tận diệt._
____
====

Bài này tôi nghe được lúc sinh tồn trong tựa game Fallout 4. Sau đó là suốt thời gian ở Melbourne, kéo dài cả vài chục phút trên tàu rời Lalor vào nội thành học nhạc.

Chắc cũng vì vòng hòa thanh và chất giọng đậm màu thập niên 60, cùng với cảm giác đơn độc trong Fallout 4 và cảnh khó khăn mùa dịch ở vùng đất cách quê nhà 7000 cây số mà bài hát này dính tôi tới vậy.

Nghe bản gốc tại https://www.youtube.com/watch?v=sonLd-32ns4[YouTube].

The Carpenters cũng có một bản thu của bài này, bạn có thể nghe https://www.youtube.com/watch?v=ThK5M8Ttzpw[tại đây].

== Love Me For What I Am (1975) - The Carpenters

image::3.avif[The Carpenters,width=350,align=center]

[.text-center]
====
____
_Hãy yêu em vì em là em, khi em là chính mình._

_Đừng yêu em vì những gì anh muốn em sẽ trở thành, và để hoàn thiện giấc mộng của riêng anh._
____
====

Bài hát nói về một cô gái không còn là chính mình khi kề cạnh với chàng trai, muốn cô luôn phải phấn đấu để thành một hình mẫu hoàn hảo trong mắt anh ấy nhưng lại không phải con người thật của cô.

Nội dung bài này mới đầu nghe có vẻ hơi ích kỷ, cả về hai phía, nhưng suy cho cùng cô ấy cũng đã kiên nhẫn chờ đợi. Một bài hát hay là khi ta có thể nhập vai vào nhân vật trong câu chuyện, trải qua những gì họ đang trải qua. Như một bộ phim, hay một mẩu chuyện ngắn.

Nghe thử tại https://www.youtube.com/watch?v=vgu5WRyhmWM[YouTube] để biết tại sao tôi yêu The Carpenters.

== Can't Smile Without You (1975) - David Martin

image::4.avif[David Martin,width=300,align=center]

[.text-center]
====
____
_Anh không thể cười nổi khi không có em._

_Anh thấy vui khi em vui, buồn khi em thấy buồn._

_Anh chẳng thể hát, chẳng thể làm gì cả._
____
====

Vẫn là cái sến của những bài xưa cũ. Bài này cũng có một https://www.youtube.com/watch?v=7D993OdK3tU[bản thu của The Carpenters] nhưng để danh sách đa dạng hơn về nghệ sĩ nên tôi quyết định để tên của https://www.youtube.com/watch?v=LAOROtxT1AQ[David Martin]. Không mọi người lại nói fan cuồng của cô Karen Carpenter... dù đó là sự thật.

Ngoài ra https://www.youtube.com/watch?v=3V_7-7myPxM[bản thu của Barry Manilow] là cộng hưởng với tôi nhất. Chắc vì lựa chọn của ông trong màu nhạc có tí tích cực hơn, đúng với cách tôi hiểu về bài hát này. Và đoạn climax (cao trào) cũng "tới công chiện" hơn.
