---
title: Già trước tuổi
tags:
  - thoughts
date: 2023-04-09
description: thử làm một người lớn tuổi
slug: gia-truoc-tuoi
---

Tôi thường dành cho mình những buổi chiều thật nhẹ.

Tất nhiên không thể thiếu một ít đăng đắng cà phê ở đầu lưỡi.

Tôi không hút thuốc vì sợ buổi chiều phải sớm không còn tôi để tâm tình.

Sợ lúc đó nó lại đem nỗi buồn xối lên đầu cổ dân Sài Gòn tội người ta.

pass:[<br>]

[.text-right]
====
Dạo gần đây tôi lại có thú vui đọc sách, tâm lý, triết học, vũ trụ, thiên nhiên.

Treo bên tai vài giai điệu êm êm của mấy bài cổ điển không có lời ca.

Tôi tháo nhận thức mình ra gắn vào câu từ, tâm hồn của tác giả.

Vô tình bỏ mặc chiều ngồi thơ thẩn cố tỏa nắng để thu hút ánh nhìn.
====

pass:[<br>]

Nhiều người nói tôi già trước tuổi, chắc tại tôi thấy người già bình yên hơn.

Người già đi chậm để nhìn ngắm cuộc đời, cảm nhận hơi thở để thấy ngày chậm trôi.

Người trẻ vụt lướt nhanh, rồi than thở sao xuân thì ngắn ngủi.

Người phóng xe điên đảo, người đi bộ lề mề, cảnh đẹp vẫn đó mà người thấy kẻ không.

pass:[<br>]

[.text-center]
_Thiệt lạ, ta tìm đủ cách giết thời gian, rồi lại não nề khi thấy nó không còn bao nhiêu._
