---
title: Về hạnh phúc
tags:
  - thoughts
  - books
date: 2023-09-22
description: vài suy nghĩ đọng lại sau một cuốn sách hay
slug: ve-hanh-phuc
---

Có một sự thật là sau ngần ấy năm tiến hoá, chúng ta không sinh ra chỉ để hạnh phúc. Mà đơn giản là phải sinh tồn và chăm lo thế hệ sau. Nhưng nếu như không có khái niệm về hạnh phúc và khổ đau, tất cả chúng ta sẽ đều nằm một chỗ. Cũng chẳng thiết sống làm gì.

Chúng ta không sinh ra để ăn no bụng, để uống đến nôn mửa, và để thưởng thức khoái lạc với mạch máu đầy N2O, hay còn gọi là khí cười.  Ăn quá dư thừa sẽ gây các chứng bệnh của người giàu, tiêu biểu là tiểu đường tuýp hai. Uống rượu bia quá nhiều thì tan nát nội tạng. Ngủ quá nhiều cũng kéo theo đủ bệnh về tim mạch, hệ miễn dịch,...

---

Có thể coi khổ đau là cơn đói hạnh phúc. Tự hỏi có khi nào do chúng ta hạnh phúc quá nhiều nên bệnh khổ đau cũng trở nên phổ biến hơn trước không?

Tôi thấy hiện tại chúng ta có vài cách khác nhau để đối phó với bệnh này:

* Một là phải xây một lịch trình thật kín để cơn đói hạnh phúc không có thời gian cồn cào. Một trong những nguyên nhân bùng nổ văn hoá _hustle_.
* Hai là phải sống chung với những cơn buồn dai dẳng thách thức ham muốn tiếp tục sống. Trầm cảm và nạn chấm dứt bản thân...
* Ba là chuyển sang chế độ bảo trì vì quá nhiều đau khổ và một nỗi bất an ngấm ngầm. Những cá nhân _ái kỷ (narcissism)_, đánh giá cao bản thân, tôn thờ cái tôi và lối sống ích kỷ.
* Bốn là cả ba cách trên... Dành cả tuổi trẻ chạy trốn nỗi buồn bằng cách vùi đầu vào công việc. Không có thời gian, năng lượng để quan tâm người khác. Và cuối  cùng đối mặt với cô đơn, rơi vào trầm cảm...

---

Những lạc thú khiến cơ thể tiết ra Dopamine, một trong những hormones hạnh phúc. Tác động chính của Dopamine liên quan chủ yếu đến hành động, trí nhớ và cảm giác khoan khoái.

Một con khỉ nhảy lên chụp được quả chuối sẽ tận hưởng không chỉ vị ngon của quả chuối đó mà còn đi kèm cảm giác sung sướng từ những hormones tiết ra từ việc làm đó. Vì thế chúng có động lực ăn uống, vận động. Việc tìm kiếm bạn đời cũng có cơ chế tương tự.

Tưởng tượng chúng ta giao cho A việc đóng mở một vòi nước theo từng mức độ. Mỗi lần nhận được một đồng xu Dopamine, A sẽ để nước chảy mạnh hơn. Một lúc sau tự dưng Dopamine quá nhiều, A mở toang vòi liên tục. Sợ bể đường ống nên tôi nói A thấy đủ 100 đồng Dopamine thì hãy mở vòi.

---

Tương tự, khi Dopamine tiết ra quá thường xuyên, các neurons sẽ thích nghi để không bị quá tải. Chúng ta sẽ cần nhiều hơn những lạc thú, đặc biệt là những thứ nhanh gọn, tức thì mới đủ để cảm thấy đã đời.

Không phải tự nhiên mà nội dung mọi người tiêu thụ ngày càng ngắn, càng tiện lợi. Ngày càng nhiều hơn những cơn nghiện, nghiện mua sắm, chửi nhau, tương tác mạng, rượu bia, cá độ, cờ bạc, nicotine... Và tất nhiên đằng sau những món nghiện ngập luôn là những tay buông chất gây nghiện rất nhiệt tình.

_Độ dính_ của một thứ nghiện ngập được quyết định không chỉ bởi lượng Dopamine tiết ra trong một lần _đạt đỉnh (high)_ hay _thời gian áp phê_. Thứ nguy hiểm hơn cả là độ có sẵn (availability) và độ dễ tiếp cận (ease of access).

---

Nội dung của một clip ngắn, một bộ phim tóm tắt trong năm phút, cảm giác hạ gục đối thủ trong phần bình luận, cảm giác ăn một canh bạc, cảm giác đập hộp một món đồ. Về bản chất cũng như việc ăn một quả chuối đối với một chú khỉ.

Thay vì loài khỉ phải vào rừng để tìm chuối ăn. Ta ngồi lướt điện thoại, lấp đầy giỏ hàng rồi bấm thanh toán, soạn bình luận dài 500 từ, trông đợi một ván tài xỉu,... Tất cả đều theo cơ chế làm hành động  A để được Dopamine.

Những cơn lũ Dopamine cuốn trôi hết những niềm hạnh phúc giản đơn. Nụ cười của cha mẹ già, một bữa cơm bên gia đình, một bài nhạc không lời cùng quyển sách cạnh cửa sổ ngập nắng.

Chúng ta hòa mình vào dòng lũ ùa ra từ màn hình điện thoại. Ngấu nghiến những món giải trí rẻ tiền, ngắn hạn rồi hoá chai lì với những niềm hạnh phúc thật sự, êm ái và bền bỉ.

[NOTE]
====
Một trong những hormones hạnh phúc khác là https://en.wikipedia.org/wiki/Serotonin[Serotonin]. Khi khoái lạc ngắn hạn và Dopamine là một cặp, thì Serotonin mới là thứ mang lại hạnh phúc bền bỉ mà ai cũng theo đuổi.

Serotonin giúp cải thiện giấc ngủ, điều hoà tiêu hoá, và nhiều thứ khác nữa. Bài viết này tôi sẽ không nói nhiều về Serotonin. Hãy để một bài viết khác hoặc bạn có thể tự tìm kiếm trên mạng.
====

---

Nên nhớ bản chất Dopamine không phải kẻ thù của ta, nhờ có hormone này mà chúng ta có động lực để tìm kiếm, đáp ứng các nhu cầu tối thiểu để duy trì sự sống. Đánh răng, rửa mặt, bước ra đường, ăn uống, hàn thuyên, tìm bạn đời. Do đó có một kỹ năng mà tôi muốn luyện tập với mục đích là để đưa nhu cầu khoái lạc và độ nhạy cảm với Dopamine về mức ổn định.

Hãy sống chậm lại! Có thể coi là sống như người già vì thời của ông bà ta không có tóm tắt phim, bóng cười, những món giải trí rẻ tiền như hiện tại. Đồng thời những thứ gây nghiện với họ hồi đó bây giờ cũng mang tiếng là lỗi thời nên ít người bán, ít có cơ hội để ta tiếp cận. Trừ rượu bia là vẫn còn...

Ăn uống vừa phải, không quá no. Ăn khi bụng cồn cào, uống khi khát. Tập thưởng thức sách. Tập nâng niu những cơn chán nản, vì đó là lúc mặt hồ trong tâm trí ta tĩnh lặng nhất, sau những trận mưa lũ xối xả từ Internet.

---

Tôi đang thử sống như vậy thời gian gần đây. Tiếc là vẫn chưa đến độ yên bình được như vậy, có lẽ nói ra nên thấy nhục nhã với bản thân vì nói được mà làm chưa được... Nhưng tôi tin đó là cách để giữ cho mình một hồ nước tâm trí yên tĩnh.

Chúng ta đang sống trong hời đại mà tâm trí con người cũng như đại dương kia, đã lắm bão tố lại còn đầy rác.

Bài viết này tôi lấy cảm hứng từ quyển Dopamine Nation bởi https://www.annalembke.com[Anna Lembke], bản dịch tiếng Việt là Giải Mã Hoóc-môn Dopamine.
