---
title: Tạm biệt Windows
tags:
  - tech
  - thoughts
date: 2023-12-21
description: những lời than thở gửi windows
slug: tam-biet-windows
---

== Tôi và phần mềm

Lớn lên trong giai đoạn công nghệ bắt đầu phổ biến ở Việt Nam, cũng có hơi trễ với bạn đồng trang lứa vì nhà cũng không khá giả. Thời đó chưa có mạng, nhà tôi mua rẻ lại một dàn máy của bạn ba tôi. Tầm bảy, tám tuổi tôi tìm được trong máy có đâu chục bài nhạc người ta quên chưa xóa, nghe đi nghe lại mãi. Giờ lớn rồi tôi vẫn còn nhớ bài https://www.youtube.com/watch?v=QZen-Wjrsv4[Chàng khờ thủy chung] bủa vây thời tay cầm chuột, mắt nhìn màn hình năm nào.

Thời cấp hai, bắt đầu bén duyên với công nghệ, tôi cài giao diện cho Windows 7 của mình, tải hình nền, dùng XWidget, Rainmeter... Biến cái máy tính để bàn của mình thành một rổ đồ chơi mỗi lần đi học về. Lớn thêm một tí, tôi mò lên mạng học Photoshop, Premiere Pro, dựng phim và vài ba trò ghép hình nham nhảm.

Sau này lên cấp ba tôi học thu âm, chỉnh âm bằng Adobe Audition, FL Studio... Tôi mua một cái audio interface, một cái mic của Audio-Technica. Tôi học khử ồn (noise filter), nén (compression), EQ... Cũng là lúc tôi phát triển kỹ năng thao tác trên máy tính của mình nhiều nhất.

== Tạm biệt Windows

Tôi đã dùng từ Windows XP đến Windows 11, theo chân Microsoft qua nhiều thời đại phần mềm của họ. Từng dính virus, treo máy, hư phần mềm, làm hỏng ram, mất dữ liệu... Tôi từng nghĩ Windows là máy tính, máy tính là Windows, chúng ta không còn lựa chọn nào khác.

Ngược đời thay... sau đây là một số lí do chính tôi ngưng hẳn việc dùng Windows.

=== Bloatware - Phần mềm thừa thãi

Đến cuối năm 2019, tôi chán ngấy với Windows 10 của mình, máy để không thôi đã ngốn gần 3GB ram. Thao tác gì cũng ù lì, vì họ cứ cập nhật thêm tính năng tôi không bao giờ đụng tới, còn máy của tôi thì vẫn cứ thế, mua từ hồi 2015. Còn dùng CPU Intel i7 thế hệ thứ 4. Tác vụ chạy ngầm của Windows nhiều và không thể tắt được vì sẽ ảnh hưởng trải nghiệm chung, dù những chức năng đó tôi không dùng...

Chẳng hạn trình duyệt Microsoft Edge, lúc đó tôi toàn dùng Google Chrome, mà Edge để không thì chiếm dung lượng và liên tục chạy ngầm, muốn gỡ đi cũng không được. Control Panel không có lựa chọn Uninstall, chỉ có thể Repair thôi. Mà chạy mấy cái scripts trên GitHub thì gỡ được vài hôm, đến khi cập nhật Windows cũng cài Edge lại trên máy.

Chưa kể gỡ được thì cũng lỗi đủ loại, launcher một vài game không mở được, vài tính năng sử dụng Edge bản webview cũng không chịu chạy. Trình tìm kiếm trong Start Menu thì không dùng trình duyệt mặc định là Google Chrome mà cứ bắt chạy Edge. Microsoft làm tôi nhớ đến thời họ ép các máy chạy Windows dùng Internet Explorer bị kiện đủ trò. Mà bây giờ họ "lồng ghép" Microsoft Edge chặt với Windows 10, 11 như thế thì chưa thấy ai nói gì...

Đó mới là nói về Edge thôi, chưa kể về Candy Crush Saga và mấy tựa game nham nhảm cài đặt đầy trong Start Menu. Windows 11 còn có cả TikTok, Facebook... nằm tỉnh bơ trong đó.

=== Riêng tư và bảo mật

Phần lớn lí do tôi bỏ Windows là vì riêng tư và bảo mật (Privacy & Security). Có thể bạn sẽ nghĩ tôi làm gì mờ ám hay sao mà sợ... vấn đề này cần một bài viết riêng trong tương lai tôi sẽ nói. Ví dụ như nhà chúng ta có rèm cửa, và bạn biết sẽ có những người dòm ngó vào nhà mình, bạn sẽ kéo rèm lại chứ? Hay sẽ để ai muốn nhìn cũng được? Việc đó tùy vào bạn, riêng tôi khi dùng máy tính luôn cần một sự riêng tư và an tâm nhất định.

Microsoft tận dụng ưu thế hệ điều hành của mình để có những trò "kiếm thêm" khá là nhạy cảm. Vào phần cài đặt của Windows bạn có thể thấy những tùy chọn và thông báo về việc thu thập dữ liệu của họ. Từ những phần mềm bạn cài trên máy, thao tác, cử chỉ, vị trí, cấu hình phần cứng, thông số máy tính, thậm chí cả những gì bạn đã, đang và sẽ gõ trên bàn phím.

Về bảo mật, cái này không thể trách Windows hẳn, vì chính sự phổ biến của họ dẫn đến nhược điểm này. Phần lớn người dùng máy tính sẽ cài Windows lên máy của mình, điều này làm Windows thành một miếng mồi thơm cho những thành phần xấu trên mạng. Các vụ mã hóa dữ liệu tống tiền, lấy cắp dữ liệu người dùng, chiếm đoạt thông tin đăng nhập, cookies trình duyệt web... hầu hết diễn ra trên Windows.

Tất nhiên Linux và macOS cũng có những lỗ hổng và phần mềm độc hại, nhưng tỉ lệ dính phải là thấp hơn rất nhiều so với Windows.

=== Phí duy trì

Phải nói thật với bạn, thuở cấp hai, cấp ba tôi toàn dùng những phần mềm "thuốc", phần mềm lậu tải về trên mạng. Từ bộ phần mềm sáng tạo của Adobe cho đến Microsoft Office. Và tôi biết phần lớn người dùng tại Việt Nam và trên thế giới vẫn còn thói quen này. Vì thật lòng mà nói giá mấy phần mềm này là quá chát với nhu cầu, cũng như thu nhập của chúng ta, và việc tải lậu một phần mềm là quá đơn giản nên dại gì mà không tận dụng chứ.

Thời gian học tại Nhạc viện Úc tôi được một tài khoản sinh viên có bao gồm gói Office 365, và nộp CoE du học để được giảm phí đăng ký Adobe Collection. Phải nói là trải nghiệm dùng đồ thật có sướng hơn đồ thuốc. Mượt mà, cài đặt cũng yên tâm không sợ dính mã độc (dù trong mấy phần mềm này cũng đầy thứ lấy dữ liệu người dùng của chính những công ty này).

Khi về Việt Nam rồi, mấy tài khoản đó cũng không còn dùng được nữa, trả giá gốc thì quá đắt so với thu nhập của tôi (0đ)... Thế nên tôi muốn tìm một hệ sinh thái công nghệ "kinh tế" hơn cho mình. Hầu hết phần mềm tôi chọn để thay thế những thứ đang dùng là phần mềm mã nguồn mở và miễn phí.

Đây là một vài phần mềm tôi đã thay bằng các phần mềm mã nguồn mở.

[%header,%autowidth,frame=ends]
|===
|Cũ | Mới
|Adobe Audition | Ardour + Tenacity
|Adobe Photoshop | GIMP
|Adobe Premiere Pro | Kdenlive
|Google Chrome | Firefox
|Google Docs | Vim
|Google News | Newsraft
|===

Trong lúc thử nghiệm những phần mềm này tôi chạy song song Windows và Linux (dual boot). Một thời gian tôi nhận ra nếu nhu cầu của mình chỉ có vậy, thì cớ gì lại phải chịu những cái phần mềm rác, trình chạy ngầm, xâm phạm quyền riêng tư... Linux trở thành một ngôi nhà mới không thể phù hợp hơn.

=== Vài lí do khác

Trên đây là những lí do chính khiến tôi không còn hứng thú với Windows. Và đây là một vài lí do phụ, không tiện kể ra chi tiết ở đây:

* Windows 11 không hỗ trợ chính thức với CPU Intel thế hệ 4 của tôi.
* Không có nhu cầu chơi game trên máy tính nữa.
* Có nhu cầu thiết kế web và lập trình nghiệp dư, cần một môi trường đơn giản hơn.
* Tò mò muốn khám phá cái gì đó mới mẻ.

== Tổng kết

Có thể nói Windows gắn liền với tuổi thơ của tôi, cũng như mấy anh chị sinh ra những năm 80, 90 cho đến các em thời nay. Từ năm 2020, tôi bước chân vào cộng đồng Linux trên YouTube và Reddit, học lỏm kinh nghiệm của họ.

Tất nhiên tôi đã không chuyển sang macOS, hệ sinh thái của Apple là một thứ gì đó vừa xa xỉ vừa xa lạ đối với tôi, ở hiện tại thôi, còn tương lai thì tôi chưa biết. Cũng có thể trong tương lai vì công việc hay gì đó tôi vẫn sẽ phải chứa Windows trong một ổ đĩa trên máy mình. Nhưng chắc chắn nó sẽ không là hệ điều hành sẽ chạy mỗi lần "bấm nút nguồn" của tôi.

Tôi sẽ có một bài viết trong tương lai về Linux, lựa chọn đúng đắn nhất của tôi tính từ ngày vọc vạch cái máy để bàn mua rẻ từ bạn ba tôi, qua mấy đời máy tính và hệ điều hành. Còn bài viết này chỉ là để chia sẻ câu chuyện của tôi. Cho dù bạn dùng Windows, macOS, Linux hay TempleOS đi nữa thì tôi cũng không bận tâm, vì đó là lựa chọn của bạn, và đó có thể đang là môi trường làm việc hiệu quả nhất với bạn.

Hy vọng tôi đã đem đến cho bạn những suy ngẫm mà tôi nghĩ là cần có trong thói quen dùng đồ công nghệ của tụi mình. Rất cảm ơn bạn đã đọc đến đây!
