---
title: Về tình yêu
tags:
  - stories
  - thoughts
date: 2024-05-16
description: chuyện của Dạ
slug: ve-tinh-yeu
---

Năm ấy hiếm khi nỗi buồn có dịp ghé thăm hai gò má của chị như dạo gần đây. Sài Gòn trở trời, nhiều mưa hơn, và đêm cũng lạnh hơn trước. Giờ này quán nước nơi chị làm mới đóng cửa. Hai vị khách cuối cùng ra về, tất nhiên là một cặp đôi, chị loay hoay lau dọn rồi kéo hạ cửa quán.

Tan ca, Dạ chạy tà tà trên con xe "tầm nhìn", nhưng tầm nhìn của chị lại đặt ở một nơi nào đó xa lắm. Lòng tự trọng của một cô gái trẻ không cho chị khẳng định là mình nhớ anh ta. Chị chỉ tự nói với lòng rằng phải chi đang ngồi sau xe, nấp sau gáy anh ta rồi mỉm cười nhẹ.

Sài Gòn đang bước vào mùa của đôi lứa yêu nhau, chị sợ cảnh cô đơn lắm. Hồi bé chỉ sợ không có búp bê, đồ hàng, giờ lại sợ cô đơn. Kể cũng lạ, thoát cô đơn đối với Dạ là không khó, có mấy tin nhắn trong hòm thư chờ chị còn chưa kịp xem. Với vài người, cô đơn không phải một dạng tai nạn như ta vẫn nghĩ, hiện thực cô đơn của Dạ là một lựa chọn. Không phải vì chị muốn cô đơn, mà chị giữ mình cô đơn để không bỏ lỡ những ước muốn còn bay bổng lắm.

---

Trong quyển nhật ký, từ xuất hiện nhiều nhất có thể là "ngốc". Dạ thường trách mình ngốc, vì chỉ có kẻ ngốc mới ra những lựa chọn mà chị đã từng. Nhưng cũng không hẳn, Dạ thấy mình cũng đâu đến nỗi, chắc ngốc vì tình là một kiểu ngốc rất khác. Vì chẳng phải khối phim ảnh và tiểu thuyết đều xoay quanh thể loại ngốc này đấy sao?

Những kẻ ngốc thường đưa ra lựa chọn sai lầm vì họ không thấy được lựa chọn đúng. Một cách nào đó, những kẻ ngốc vì tình còn ngốc hơn một kẻ ngốc bình thường, họ luôn thấy lựa chọn đúng nhưng lại cố ý chọn cái sai rành rành.

Dạ lắc đầu, không thể như vậy, phải có lí do gì chứ. "Những giấc mơ! Đúng rồi! Là những giấc mơ", chị khoái chí thấy mình như vừa chứng minh được là mình không hề ngốc. Người ta dằn vặt sau một cuộc tình không chỉ vì những chuyện đã từng, mà còn vì nuối tiếc những giấc mơ, những chuyện "có thể sẽ là đã từng".

---

Bởi do vậy mà càng lớn, càng trải qua nhiều lần ngốc, người ta càng ít mơ mộng. Ta tỉnh táo hơn, vì có ai nằm mơ khi mắt mở trao tráo bao giờ. Dạ thường rửa mặt cho tỉnh ngủ bằng những màn chia tay đình đám trên mạng, mất niềm tin vào thứ rung động đầy chất bản năng.

Tình yêu với Dạ không còn là câu chuyện thơ mộng và đầy hy vọng, chị xem tình yêu như trò chơi điện tử, như một bữa cà phê với bạn bè. Tình yêu chỉ thoáng qua, hai con người chạm mặt nhau, gặp nhau vài lần, trở thành thói quen, được thì cứ thế bên nhau, không thì lại mỗi người mỗi ngã.

Tình yêu không còn thiêng liêng như thời mười chín, hai mươi tuổi, không còn là bắt buộc, không là thứ đáng đua đòi. Dạ xây một thế giới của riêng mình, nơi đó không cần tình yêu chị vẫn an nhiên và hạnh phúc. Chỉ đến khi cô đơn làm mắt chị nhiều lần sưng lên vì khóc.

---

Đời vốn luôn thích thử thách ta bằng những đợt sóng cảm xúc. Mùa hạ năm nay tưới lên Dạ một tràn những làn mưa tình tứ, chị nhạy cảm hơn, muốn mở lòng, và chịu khó học cách thương một người như chị của những lần chưa biết đau. Chị cứ tưởng mình đã chai sạn với tình yêu, cứ tưởng tâm trí này không thể chứa thêm ai được, lại một lần nữa, Dạ lầm to.

Chị giống loài cua, loài tôm ngoài khơi, vỏ tuy có cứng cáp nhưng vốn là để bảo vệ bản chất mềm mỏng bên trong. Có vẻ như vai diễn nữ doanh nhân độc thân là thứ chị muốn, nhưng không phải điều tâm trí Dạ cần. Vì cũng như bao con người khác trên mặt đất, chúng ta mắc trong mình căn bệnh cô đơn.

Cô đơn là bệnh muôn thuở của con người, ta cô đơn trong bộ óc của mình, ta có thể mời người khác vào nhà uống trà hàn thuyên, nhưng tâm trí thì muôn đời là ngôi nhà không có lối vào. Bạn có thể mô tả nó cho người khác, nhưng chẳng bao giờ có thể mời người khác vào chơi cho dù cả hai đều rất muốn.

---

Tình yêu là nguồn sáng duy nhất của ngôi nhà tâm trí, tình yêu sưởi ấm, lấp nó bằng thứ năng lượng của một tâm hồn cô đơn khác. Dạ không thể mời người khác đặt chân vào tâm trí của chị, nhưng chị đang rất thèm kể nó với một người, chị muốn họ cảm nhận được ngôi nhà của mình, đồng thời cũng muốn nhìn ngắm và sưới ấm ngôi nhà của một ai đó.

Tình yêu không phải một buổi cà phê ngắn ngủi, tình yêu là bếp than hồng âm ỉ cháy trong ngôi nhà tâm trí sơ hở là hạ nhiệt lạnh toát. Thật khó để tưởng tượng con người sẽ ra sao nếu không có tình yêu. Mạnh mẽ, độc lập là những tính từ ta dùng để đánh lừa mình, để nghĩ là mình không cần yêu đương.

Giống như nhịn một bữa ăn thấy không hề khó chịu nên nghĩ rằng ăn uống là thứ chỉ tổ dư thừa và phiền phức. Dạ nhịn được vài bữa ăn, chị thấy mình vẫn ổn, nhưng ngôi nhà của chị đã lạnh căm, dần đóng thành băng, chỉ cần một va chạm nhẹ là vỡ toang như viên đá trong ly nước sáng nay chị mang ra cho khách.

---

Rõ là thế rồi, chị không thể thiếu tình yêu, không phải vì chị không mạnh mẽ, mà vì mạnh mẽ không phải là công cụ để chống chịu nỗi cô đơn. Mạnh mẽ có thể xoa dịu nó, hay làm ta nghĩ rằng mình không tổn thương, như thuốc giảm đau mỗi lần trời trở gió, gặp cơn nhức đầu chị hay uống.

Quen với nỗi đau gây ra bởi cô đơn không có nghĩa đã quen với cô đơn, một ngày nỗi đau đủ lớn, ta lại thành ra tan tành, vụn vỡ. Vì mỉa mai thay, chỉ có những thứ chai sạn, cứng cáp thì mới có thể vỡ vụn, mềm mỏng như mật ong thì có biết vỡ là gì.

Một cách nào đó, quen với cô đơn lại là thứ nguy hiểm hơn đơn thuần nỗi cô đơn. Khi đã quen với cô đơn, đôi lúc ta vẫn sẽ thấy quạnh hiu, trống vắng, lại nghĩ mình chả cần ai khác, chắc chỉ là cảm xúc nhất thời thôi. Làm gì đó cho quên đi cảm giác cô đơn không có nghĩa là ta không bị nó làm tổn thương.

---

Trái tim của Dạ _(nói một cách văn chương)_ chắc đầy những vết thương sau mỗi lần cô đơn ghé thăm, chị nghĩ là mình ổn, nhưng đâu đó trong vô thức, vẫn có tiếng gọi của một Dạ bị chôn vùi dưới lớp vỏ bọc mạnh mẽ. Dạ ở đó vẫn mộng mơ, tràn đầy hy vọng và chìm trong những mùa mưa của ngày mười chín, hai mươi.

Dạ ở đó vẫn nâng niu cái hôn đầu như cô học trò cuối cấp, tô tô vẽ vẽ chùm hoa phượng và những hàng ghế đá cũ mèm, mẻ chỗ ngồi, vỡ tấm lưng. Dạ thấy mình vẫn cần tình yêu, chỉ là chị đã bỏ bê cô gái trong mình một thời gian dài.

Ngẫm thấy yêu thương là một mối giao kèo, đắp nên từ hy vọng, niềm tin và sự cống hiến. Chị đang thiếu cả ba, ở hướng cho đi, cũng thiếu luôn ở chiều nhận lại.

---

Dạ về đến nhà, không bước vào ngay dù trời đã tối, chị đứng trước cửa nhìn về phía cây bông giấy đầu hẻm, tối nay chị thấy mình mộng mơ, chị mơ về mấy cánh bông giấy trong túi áo khoác...

Dạo này quán có anh khách quen, hay ngồi cạnh cửa sổ, đều đặn gọi một ly bạc xỉu. Anh nhìn Dạ mãi, lâu lâu bắt gặp ánh mắt chị ghé qua, tưởng được Dạ nhìn, ảnh cười tươi rối. Mà anh ơi, Dạ không phải nhìn anh đâu, anh ngồi ngay cửa sổ, chỗ nhân viên coi có khách tới không để còn ra phục vụ đấy.

Hôm qua lúc ra về anh có để lại tờ giấy trên bàn. Chị tưởng anh quên định kêu lên, nhìn ra thì thấy anh đang đội nón bảo hiểm, miệng bày đặt làm khẩu hình "em đọc đi!". Dạ cũng ngờ ngợ hiểu, anh có kẹp mấy cánh bông giấy đằng sau, trước có hai dòng chữ cũng nghiêng nghiêng, đẹp đẹp.

[.text-center]
====
> _Nay được gặp em, khách quen, người lạ_
>
> _Chỉ ước một ngày, người lạ thành quen._
====

Chị đỏ mặt một hồi, nhìn ra thì thấy anh đã đi mất. Tối nay mặt chị cũng đang đỏ hồng như màu bông giấy, thôi xong... kiểu này là lại yêu rồi Dạ ơi!
