---
title: Bàn về ham muốn
tags:
  - books
  - thoughts
date: 2024-03-11
description: một quyển sách cho người muốn an vị
slug: ban-ve-ham-muon
---
== Giới thiệu

Tôi cầm quyển sách này trên tay vào một lần cao hứng muốn tìm hiểu về triết học. _"Tại sao ta muốn thứ mà ta muốn? Chắc sẽ là một quyển khó đọc lắm đây..._", tôi nghĩ thầm.

Tác giả quyển sách này là https://www.williambirvine.com[William B. Irvine] một giáo sư triết học. Ông thực hiện công tác giảng dạy tại trường Đại học https://www.wright.edu[Wright State], Mỹ. Trang bị cho mình một nền kiến thức dày dặn về triết học, ông dẫn dắt chúng ta đi tìm bản chất của những ham muốn.

Trước khi đọc quyển sách này, tôi có mang trong mình một ý tưởng. Có vẻ như hầu hết nỗi khổ của chúng ta xuất phát từ việc _không có được thứ mình muốn_ (tình yêu, tiền bạc, danh lợi, địa vị...) Thế thì tìm hiểu bản chất của ham muốn có vẻ là cách trị tận gốc mầm mống của nỗi khổ.

---

Ban đầu tôi có một định kiến với các quyển sách triết học, rằng lời lẽ, văn phông sẽ rất khó hiểu. Nhưng có vẻ nhờ công của nhóm dịch, quyển sách thật sự rất dễ tiếp cận. Tất nhiên sẽ không có gì đáng nói nếu như đây là một cuốn tiểu thuyết, nhưng đối với một quyển triết học thì để làm được vậy là rất hay!

Ông có liên hệ về góc nhìn của một vài tôn giáo về ham muốn. Quả thật là một người có trình độ trong triết học và tư duy rộng mở, ông nhắc đến với mục đích tham khảo và hoàn toàn không phê phán hay chỉ trích gì những tôn giáo đã nhắc đến. Đối với tôi, việc giữ một góc nhìn trung lập khi đề cập đến những vấn đề như tôn giáo thật sự rất khó.

Không chỉ dừng lại ở việc phân tích nguồn ngọn, ý nghĩa, và cơ chế của ham muốn. Tác giả còn dành ra gần nửa quyển sách nói về cách đối đầu với những ham muốn. Như một bước trở mình từ một quyển triết học thành một quyển self-help chính hiệu, có gốc rễ, đầu đuôi và không qua loa như phần lớn những cuốn sách self-help khác.

Việc đọc quyển sách này cũng góp phần rèn luyện tư duy phản biện như một triết gia, những phát ngôn liên tục được đưa ra và mổ xẻ tìm ra điểm yếu, điểm mạnh. Mục đích là để tìm được chân lý, và sự thật tuyệt đối.

Tác giả phân chia bố cục quyển sách rất hợp lý, dẫn dắt người đọc tìm hiểu có ngọn nguồn, theo trình tự. Ban đầu ông nói về bản chất, những đặc tính của ham muốn. Phần giữa ông nói về nguồn gốc của ham muốn, cũng là phần mà theo tôi là hay nhất quyển sách. Nửa còn lại ông nói về cách đối đầu với những ham muốn, phần này tách riêng ra cũng đủ làm một quyển sách độc lập.

---

Tôi nghĩ đây là một bước đầu hoàn hảo cho những ai chưa từng tìm hiểu về triết học và đang có ý định làm điều đó. Vì nội dung quyển sách tuy có dài, nhưng rất gần gũi. Và ham muốn cũng là thứ chúng ta đối mặt hàng ngày nên dành thời gian tìm hiểu về nó thật sự là xứng đáng!

Đây là một chủ đề triết học mà theo tôi là rất thiết thực, không như những chủ đề trừu tượng, cao siêu, và mơ hồ khác. Có hơi tâng bốc nhưng đối với tôi, những tư tưởng này là dành cho tất cả mọi người.

Chúng ta đang sống trong thời đại mà ham muốn của ta là nguồn thu nhập của rất nhiều công ty lớn. Để làm một người tiêu dùng thông minh thay vì một con mồi dễ dụ, ai ai cũng nên trang bị cho mình những tư tưởng đúng về ham muốn.

== Trích dẫn

> [...] vì con người thường không thực sự biết được lý do tại sao họ lại muốn thứ mà họ muốn.

> Khi thỏa thuận với trí tuệ, cảm xúc không dùng lý lẽ để hợp tác. Thay vào đó, chúng làm trí tuệ mệt mỏi bằng những lời nài nỉ.

> Về mặt nào đó, chúng ta bị mắc kẹt trong tính cách của mình.

> Những người khắc kỷ không phản đối việc tận hưởng những điều mà cuộc đời mang lại, bao gồm sự giàu sang, tình bạn và sức khỏe, nhưng họ khuyên chúng ta tận hưởng chúng theo cách không biến ta thành nô lệ cho việc hưởng thụ chúng.
