---
title: Một lần cuối không phải cuối cùng
tags:
  - stories
date: 2023-12-16
description: lại là chuyện của Nghi
slug: mot-lan-cuoi-khong-phai-cuoi-cung
---

[.text-center]
====
> _"Dù em có làm anh đau một nghìn lần,_
>
> _thì lần thứ một nghìn linh một vẫn xin nguyện làm kẻ yêu em."_
====

pass:[<br>]

Dòng chữ cuối cùng anh ấy viết trong quyển nhật ký đã úa màu bởi những giọt sương đêm. Nghi vẫn hay trộm nhìn em vài ba giây mấy lần chạy xe ngang quán nước hồi đấy hay ghé chở em về. Trong quả óc của kẻ lụy tình không có chỗ cho lý trí nép mình. Chắc cũng vì anh ấy đã dọn trống cả mảng tường trong tâm trí để dán đầy hình ảnh của em.

Tối hôm ấy em tan ca trễ hơn mọi ngày, Nghi đứng đầu hẻm chờ em ra về. Người con gái từng là của Nghi hí hửng cười cùng mấy bạn làm cùng quán, liếc mắt sang thấy anh đang đứng chờ tay vẫy vẫy, nụ cười của em sáng hơn. Ánh đèn vàng dịu in bóng nhánh bằng lăng xuống mặt đường, để dành một ít ánh sáng ấm đượm đó làm long lanh mắt em và nụ cười vẫn chưa tắt lúc đã ngồi chễm chệ yên sau và tay ôm chặt Nghi, cằm thì gác lên vai anh ấy.

Những câu chuyện của một buổi phục vụ quán nước xôn xao suốt quãng đường từ quán tới tiệm cà phê 24/7 nằm ở một góc đường giờ đó đã vắng người của Sài Gòn. Hồi đó Nghi và em thương nhau bình dị. Chuyện buồn chuyện vui kể nhau nghe, hai người như là quyển nhật ký của nhau. Chắc tình yêu tóm lại cũng chỉ cần có vậy, vì cuộc đời là quá ngắn, còn buồn vui thì xếp hàng chờ được thấm vào lòng người, ai cũng cần lắm một người để chung vui, để khóc cùng.

---

Trời hôm ấy đổ một trận mưa tầm tã xuống Sài Gòn như cổ vũ cho đôi lứa yêu nhau hãy ngồi lại quán nước thật lâu. Cũng may là lựa quán mở xuyên đêm, không lại phải va vào ánh mắt xua đuổi của mấy bạn phục vụ. Nghi và em ngồi hàn thuyên đến quá nửa đêm. Nghi thích nói, anh có thể nói hàng giờ liền, anh cũng có chút vui tính, nên việc ngồi nghe anh nói cũng rất nhẹ lòng.

Em thì thích cười, chắc vì vậy mà Nghi thương em, cuộc đời của Nghi cần lắm thật nhiều nụ cười, nhất là nụ cười của em. Nghi giống một tên hề bất đắc dĩ, lòng anh thì nặng lắm mấy chuyện u buồn của quá khứ, hiện tại và cả tương lai. Anh hay làm gã hề để thấy những người xung quanh mình cười. Anh nghĩ nếu mình có thảm hại, thì ít nhất cũng có thể mang đến nụ cười cho họ.

---

Xin em đừng nghĩ Nghi lúc nào cũng vui nhé, dù trước mắt em anh ấy tích cực lắm. Những ngày gần đây bởi không còn được đón em nữa, Nghi như mặt trời của buổi chiều tà, lấp ló sau mấy tòa cao ốc, lùi về phía nền trời và đượm một màu cam đỏ buồn man mát. Anh ghé sang quán nước, đứng dưới nhánh bằng lăng quen thuộc, tắt máy xe, rồi lặng nhìn người con gái từng là của mình, lần này chỉ mong em đừng nhìn ra cửa. Nghi sợ em cười với mình, mà cũng sợ em nhìn anh ấy mà không thèm mỉm cười.

Tốt nhất thì hãy xem anh ấy như kẻ vô hình, như bóng ma của thành phố những kẻ lụy tình, và lướt qua anh ấy như hai người lạ nếu có gặp lại ngoài đường lộ. Và em ơi đừng đi quán nước 24/7 lần đó nữa. Nghi ngồi quán đó mãi, đêm đó như đoạn phim cũ anh không quên được, trách nụ cười em rực rỡ, trách Sài Gòn đổ mưa, và trách cái hôn vội lúc ra về.
