---
title: Bên kia bức màn
tags:
  - thoughts
date: 2024-01-04
description: bàn về cái chết của thể xác
slug: ben-kia-buc-man

---

== Lời dẫn

Tôi đang dần hồi phục sau chuỗi ngày chịu đựng chứng rối loạn lo âu kéo dài hơn ba tháng. Mọi thứ trở nên đáng sợ khi cơ thể trải qua những cơn tăng huyết áp và nhịp tim đột ngột. Tôi cảm nhận được lồng ngực mình đang thoi thóp vì trái tim không chịu vâng lời, mọi thứ diễn ra chậm hơn nhưng lại thiếu tỉnh táo. Tôi đã đi khám tim mạch, siêu âm tim, chụp cắt lớp ổ bụng, ngực, xét nghiệm mọi thứ có thể xét nghiệm, không hề có triệu chứng gì bất thường theo lời của bác sĩ.

Một lời khuyên tôi nhận được từ họ là bớt suy nghĩ, thay đổi lối sống, bỏ căng thẳng, lo âu. Từ đó tôi mới để ý tới những suy nghĩ thường ngày của mình. Cũng do vậy mà tôi muốn nhân dịp này gửi đến bạn một lời khuyên, hãy xem lại _"lịch sử suy nghĩ"_ của bạn trong ngày hôm nay, bạn đã nghĩ gì, lo âu điều gì, trách móc ai, buồn chuyện gì... hãy điểm danh chúng, sau đó xét lại có nên nuôi dưỡng chúng trong tâm trí của mình hay không.

Chủ đề của bài viết này không phải về rối loạn lo âu hay quản lý suy nghĩ. Những cơn hoảng loạn liên tục nhắc tôi về một nỗi sợ mà chắc ai cũng có, sợ chết. Càng có nhiều mối quan hệ, nhiều tài sản, nhiều tham vọng ta càng sợ chết, sợ mất đi thứ ta đang có và những cơ hội trong tương lai. Nỗi sợ chết ăn sâu vào bản năng của chúng ta, ta sợ rắn vì tổ tiên từng có người mất vì nọc rắn, ta sợ lửa, lạnh, bóng tối, độ cao vì cùng một lí do tương tự. Chúng ta, một loài động vật như bao loài động thực vật khác, được in vào DNA một nhiệm vụ đơn giản... _đừng chết_.

== Bản chất cái chết

Theo như tầm hiểu biết của khoa học hiện đại thì có thể xem chết là hết, ít nhất là về phần vật chất. Bạn có thể là một người theo đạo và tin vào việc tồn tại một thế giới tâm linh, nhưng ở đây tôi xin không bàn về tôn giáo, vì đó là một chủ đề rất rộng và dễ gây mâu thuẫn.

Quan trọng nhất là bất kể bạn thuộc trường phái triết học nào, đa thần, độc thần hay vô thần, chết vẫn là cái gì đó ám ảnh và ta sẽ bằng mọi cách ngăn chặn, né tránh nó. Hoặc cho dù không sợ chết thì khi đứng trước hai lựa chọn trong lúc đang khỏe mạnh rằng một là sẽ sống tiếp, hai là sẽ chết ngay lúc này, tôi nghĩ sẽ chẳng có ai chọn chết đi, trừ những người thật sự bất mãn với cuộc sống, hoặc đang mắc chứng trầm cảm nặng.

Để tiếp tục bài viết này, tôi xin giữ một quan điểm cốt lõi rằng chết là hết, sự chết đi là đoạn kết của sự sống, sự ý thức về thân xác, về danh tính này, ở thực tại này. Rằng chết là sự mất đi quyền kiểm soát cơ thể này, nhận thức này và bộ não này.

.link:https://en.wikipedia.org/wiki/Mark_Twain[Mark Twain]
> Tôi không sợ chết, tôi từng chết hàng tỉ năm trước khi tôi ra đời, và suốt giai đoạn đó tôi chẳng thấy khó chịu gì cả.

.link:https://harukimurakami.com/[Haruki Murakami]
> Cái chết không phải là phía đối lập mà là một phần của sự sống.

.link:https://chatgpt.com/[ChatGPT 3.5]
> Cái chết là một phần tự nhiên của cuộc sống, đôi khi đau buồn nhưng cũng là một cơ hội để chúng ta suy nghĩ về ý nghĩa của cuộc sống và sống mỗi ngày một cách ý nghĩa hơn.

== Cái chết của xác thịt

[NOTE]
====
Đây có thể xem là một phiên bản mở rộng hơn, đào sâu hơn chủ đề của bài viết link:/mot-mo-hat[Một mớ hạt].
====

Thể xác con người và vạn vật xét về sinh hóa, vật lý rất chi là phức tạp. Nhưng suy cho cùng, lại là thứ dễ hình dung nhất khi ta nghĩ về cái chết. Nó sẽ tan rã, thối rữa theo thời gian, nguồn năng lượng dùng để gắn kết các tế bào, mô cơ sẽ cạn kiệt và chúng sẽ phân rã thành các nguyên tố hóa học riêng lẻ, các hạt cơ bản nổi trôi trong vũ trụ. Chúng ta, về phần xác thịt khi chết rồi cũng như thân cây trong rừng hay các loài động vật, hòa vào môi trường, chút thì thấm vào đất, chút thì bốc thành hơi, chút thì theo gió bay đi.

Nếu nghĩ một cách nông cạn, ta sẽ thấy vậy là hết, hình hài này, đôi mắt này không còn hiện diện nữa, nghĩa là nó đã chết, đã tan biến. Đây là một quan niệm sai lầm và đầy thiếu sót.

Trong cuộc vấn đáp nọ giữa thiền sư Thích Nhất Hạnh và một người phụ nữ đã vào tuổi xế chiều, bà hỏi ông về luân hồi, một quan niệm gắn liền với hầu hết những người theo đạo Phật. Ông bắt đầu trả lời bằng một ví dụ về chén trà trước mặt mình. Tôi xin được phép dùng lời văn của mình thay vì trích y như lời ông.

Người bình thường khi con mắt còn bị kẹt vào cái tướng, nhìn chén trà sẽ chỉ thấy chén trà. Khi chúng ta đã qua thời gian chiêm nghiệm, chén trà sẽ không đơn thuần là chén trà nữa, ta sẽ thấy những phân tử nước, ta thấy những thứ tí hon này từng trôi theo dòng sông, từng là một đám mây lững lờ, từng nằm trong lòng đất, từng nằm trong mạch máu của mọi người. Phân tử nước thì được cấu thành từ hai nguyên tử Hydro và một nguyên tử Oxy, mỗi hơi thở của ta đều có chúng, có hơi ẩm, có Oxy... Oxy này sẽ đi vào phổi, vào máu, nuôi cơ thể ta, giúp bộ não hoạt động, giúp ta có ý thức. Người đã nghiệm ra cho mình được con mắt vô tướng khi nhìn chén trà sẽ không chỉ thấy chén trà, họ còn có thể thấy mây, thấy sông hồ, thấy vạn vật và thấy mình trong đó.

Tướng ở đây chúng ta có thể hiểu là sự biểu lộ, sự gọi tên, ta nhìn một vật thể hình bán cầu có chứa một thứ dung dịch, ta gọi đó là chén trà. Ta nhìn một khối chất hữu cơ, có năng lượng, có nhiệt độ, có hành động, lời nói, ta gọi đó là cha, là mẹ. Và cũng một thứ thân thể đó nhưng chứa đựng mọi trải nghiệm của ta, ta gọi là tôi, là mình.

Vô tướng nghĩa là nhìn vạn vật bằng con mắt sâu sắc nhất, nhìn mọi thứ dưới dạng bản chất của nó. Chính vì dùng con mắt chưa nhìn qua được cái tướng, gọi tên và cho rằng đây là tôi đầy thiếu sót và nông cạn mà cái chết lại trở thành một thứ đáng sợ và vĩnh hằng. Để làm rõ luận điểm này, hãy thử hỏi chén trà rằng:

"Này chén trà, bạn có sợ chết không?"

"Bạn thấy đấy, thật ra tôi không chỉ là tôi, tôi là sản phẩm cấu thành từ các phân tử nước, ion, khoáng chất trong trà, và phân tử của gốm, sứ. Bạn hãy hỏi họ chứ tôi chỉ là tổ hợp của các bạn ấy thôi."

Ta lại tiếp tục tiến lại gần hơn ở mức độ phân tử, "Này các phân tử nước, các bạn có chết đi không?"

Các phân tử nước nhốn nháo đồng thanh trả lời, "Bạn thấy đấy, chúng tôi chỉ là sản phẩm cấu thành từ các hạt electron tồn tại xung quanh hạt nhân gồm các hạt neutron và proton dính với nhau thôi. Sự sống chết của chúng tôi tùy thuộc vào bọn họ ấy."

Cứ thế ta càng tiến lại gần, họ lại càng kêu ta hỏi các thành phần nhỏ hơn, và điều này hoàn toàn hợp lý. Sau một hồi, ly trà tự nhiên biến mất, chúng ta chỉ thấy một trật tự, một sự sắp đặt, sự tương tác với nhau giữa những hạt cơ bản, những thành tố nhỏ hơn. Cái mà ta gọi là chén trà đã hoàn toàn biến mất, biến mất không phải vì chén trà không tồn tại nữa, mà là cái danh, cái hiện diện của chén trà đã được giải mã. Ta đã nhìn xuyên qua bức màn mà trên đó có sự hiện diện của chén trà, đồng nghĩa việc ta không chỉ thấy chén trà, mà thấy luôn những thứ cấu thành nên nó, lịch sử của nó, _"kiếp trước"_ của nó.

Hay nói cách khác, việc gọi tên sự vật hiện tượng là một lời nói dối có chủ đích, một sự giả mạo có công dụng là làm tiện lợi cho việc giao tiếp giữa người với người. Việc dùng con mắt vô tướng trong giao tiếp sẽ thật nực cười. Chẳng hạn tôi muốn nhờ người phục vụ quán nước rót lại ly trà đá giùm mình:

"Này đống chất hữu cơ ơi hãy dùng năng lượng từ việc phân giải phân tử ATP của bạn để điều khiển mớ cơ kia rót vào vật thể được cấu thành từ các phân tử thủy tinh trước mặt tôi - một đống chất hữu cơ đang tạo ra âm thanh này - một ít phân tử nước cùng các phân tử từng nằm trong lá trà kia được không..."

Tóm lại, về phần thể xác, chúng ta _không thể chết_. Vì nói một cách thẳng thắn, tôi và bạn _chưa từng tồn tại_, cái chết về thể xác là sự biến mất của thứ vật chất từng tồn tại, khi chúng ta chết đi, về phần vật chất đâu có gì mất đi. Chúng ta là sự sắp đặt, một trật tự của những thành tố nhỏ hơn, và trong cuộc đời này, trong khoảng thời gian này, các hạt này sẽ kết dính lại tạo thành cái ta gọi là cơ thể. Và chắc chắn sẽ có một ngày chúng không còn đủ năng lượng để dính với nhau hoặc bản thiết kế mang tên DNA mờ nhạt và sai lệch dần, dẫn đến việc già đi, tóc bạc, ung thư...

Giống như việc siêu âm vậy, mắt người nhìn vào bụng chỉ thấy da, lỗ rốn và lông lá, nhưng dùng một thiết bị nhìn xuyên được lớp vật chất đó, ta sẽ thấy nội tạng, tim phổi, dạ dày... Việc bỏ đi thói quen phụ thuộc vào cái tướng giống như vén bức màn sang một bên. Bên kia bức màn hoàn toàn không có bạn và tôi, chỉ có những mớ hạt chất chồng, đan lấy nhau, trôi trong không gian, nơi đó không có cái gì chết đi và sinh ra, chỉ có sự thay đổi không ngừng.

Có điều là hầu hết khi nói về phần thể xác, cái chúng ta sợ là cái đau đớn trước khi chết, chứ chưa hẳn là sợ chết. Tôi từng nghe về hoàn cảnh qua đời của các cụ trong gia đình mình, có cụ ra đi trong một giấc ngủ, hơi thở chậm dần rồi cứ thế ngưng hẳn. Một cuộc chia ly sự sống đầy thanh thản, lạ kỳ ta có thể thấy cái chết lúc này có vẻ dễ chịu, nhẹ nhàng và một cách hơi ngược đời nhưng lại _đáng mong đợi_...

== Kết lại

Như đã nói ở đoạn đầu, dù đã tham khảo và xây dựng một ý niệm về cái chết là không thể tránh khỏi và có phần không kinh khủng như ta nghĩ, nhưng một cách bản năng, tôi vẫn sợ chết, hay ít nhất là nếu được chọn giữa hai lựa chọn, tôi vẫn chọn sống tiếp!

Có thể đọc đến đây bạn sẽ thấy như bị bỏ lửng, thấy cuộc đời này với tôi sao vô nghĩa quá vậy... Cuối cùng là từ chối cái chết vì chưa từng tồn tại, xàm xí thế!

Bạn cảm thấy như vậy là cũng dễ hiểu, vì tôi chưa nói hết quan niệm của mình về cái chết mà! Ở bài viết tiếp theo tôi sẽ nói thêm về cái chết, chính xác hơn là link:/su-quen-lang[sự quên lãng], hy vọng là sẽ giải quyết được khao khát tìm lại _"ý nghĩa cuộc đời"_ đã được châm ngòi ở bài viết này.
