---
title: Luỵ - Tập thơ
tags:
  - poetry
date: 2023-08-03
description: nhiều bài thơ, gửi một người
slug: luy-tap-tho
---

Tập thơ này tôi viết vào những ngày tâm trạng treo trên nhánh bông giấy đối diện nhà. Mấy bài này không xếp theo thứ tự gì cả, cũng không có theo thể thống gì, đơn giản là nhiều chữ trong đầu nên viết ra cho bớt suy nghĩ. Bởi vì đây là tập thơ nên tất nhiên chúng không liên quan về mặt bố cục hay thể loại... nhưng chủ thể đằng sau những câu thơ thì có thể chỉ là một người...

---

[.text-center]
====
_Anh ước lối em về hàng cây nghiêng nắng_

_Ước má môi hồng không vết thời gian_

_Ước đêm thâu em nằm yên giấc ngủ_

_Chẳng u buồn, cũng chẳng nhớ về anh._

pass:[<br>]

_Sài Gòn vắng em buồn như sóng vỗ_

_Nắng hanh vàng lau mắt lệ chưa khô_

_Em về chưa hay lang thang ngoài phố_

_Chút ân tình lấy màu buồn ra tô._


pass:[<br>]


_Ban công, cà phê, màn sương sớm_

_Đêm không ngủ nghê, ngày đến vội_

_Tiếng ghi ta, lời ca của chú_

_"Bỏ mặc tôi ngồi giữa đời trôi"._


pass:[<br>]


_Anh vẽ nỗi nhớ em thành con chữ_

_Và viết tiếng em cười thành lời ca_

_Đun ấm trà toả mùi thương vị nhớ_

_Rót vào lòng để ngỡ vẫn còn em._


pass:[<br>]


_"Em có nghe mùa thu mưa giăng lá đổ"_

_Cũng tại thu buồn anh mới hận mùa thu_

_Không có em mùa thu mưa giăng lá đổ_

_Mưa ở trong lòng, lá nỗi nhớ vàng rơi._


pass:[<br>]


_Bụi hoa giấy nhớ em thu mình khóc_

_Anh cũng vậy nhưng lệ giấu đằng trong_

_Loài sẻ nhớ em nên vang tiếng gọi_

_Anh gọi Mặt Trời đốt nắng tìm em._
====
